server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Patient Microservice"
    description: "HealthCare Application - MS Patient"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eurekaserver:8070/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/patientdb
    username: root
    password: azerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true