server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  shutdown:
    enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Patient Microservice"
    description: "HealthCare Application - MS Patient"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}
      #defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaserver:8070/eureka/}

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/patientdb
    #url: jdbc:mysql://patientdb:3306/patientdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
