server:
  port: 9010

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Web App Microservice"
    description: "HealthCare Application - Web App"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    fail-fast: true
    retry:
      enabled: false
    config:
      override-none: true
  profiles:
    active: default
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
